DROP TABLE IF EXISTS countries;

CREATE TABLE countries (country_code TEXT NOT NULL, full_name TEXT NOT NULL);

INSERT INTO "countries" ("country_code", "full_name") VALUES ('AF', 'Afghanistan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AX', 'Åland Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AL', 'Albania');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('DZ', 'Algeria');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AS', 'American Samoa');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AD', 'Andorra');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AO', 'Angola');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AI', 'Anguilla');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AQ', 'Antarctica');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AG', 'Antigua & Barbuda');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AR', 'Argentina');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AM', 'Armenia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AW', 'Aruba');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AC', 'Ascension Island');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AU', 'Australia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AT', 'Austria');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AZ', 'Azerbaijan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BS', 'Bahamas');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BH', 'Bahrain');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BD', 'Bangladesh');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BB', 'Barbados');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BY', 'Belarus');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BE', 'Belgium');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BZ', 'Belize');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BJ', 'Benin');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BM', 'Bermuda');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BT', 'Bhutan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BO', 'Bolivia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BA', 'Bosnia & Herzegovina');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BW', 'Botswana');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BR', 'Brazil');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('VG', 'British Virgin Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BN', 'Brunei');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BG', 'Bulgaria');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BI', 'Burundi');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KH', 'Cambodia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CM', 'Cameroon');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CA', 'Canada');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IC', 'Canary Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CV', 'Cape Verde');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BQ', 'Caribbean Netherlands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KY', 'Cayman Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CF', 'Central African Republic');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('EA', 'Ceuta & Melilla');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TD', 'Chad');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CL', 'Chile');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CN', 'China');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CX', 'Christmas Island');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CO', 'Colombia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KM', 'Comoros');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CK', 'Cook Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CR', 'Costa Rica');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('HR', 'Croatia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CU', 'Cuba');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CW', 'Curaçao');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CY', 'Cyprus');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CZ', 'Czechia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('DK', 'Denmark');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('DJ', 'Djibouti');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('DM', 'Dominica');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('DO', 'Dominican Republic');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('EC', 'Ecuador');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('EG', 'Egypt');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SV', 'El Salvador');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ER', 'Eritrea');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('EE', 'Estonia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SZ', 'Eswatini');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ET', 'Ethiopia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('FK', 'Falkland Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('FO', 'Faroe Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('FJ', 'Fiji');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('FI', 'Finland');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('FR', 'France');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GF', 'French Guiana');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PF', 'French Polynesia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TF', 'French Southern Territories');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GA', 'Gabon');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GM', 'Gambia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GE', 'Georgia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('DE', 'Germany');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GH', 'Ghana');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GI', 'Gibraltar');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GR', 'Greece');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GL', 'Greenland');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GD', 'Grenada');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GU', 'Guam');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GT', 'Guatemala');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GG', 'Guernsey');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GN', 'Guinea');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GW', 'Guinea-Bissau');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GY', 'Guyana');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('HT', 'Haiti');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('HN', 'Honduras');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('HK', 'Hong Kong SAR China');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('HU', 'Hungary');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IS', 'Iceland');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IN', 'India');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ID', 'Indonesia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IR', 'Iran');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IQ', 'Iraq');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IE', 'Ireland');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IM', 'Isle of Man');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IL', 'Israel');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('IT', 'Italy');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('JM', 'Jamaica');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('JP', 'Japan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('JE', 'Jersey');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('JO', 'Jordan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KZ', 'Kazakhstan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KE', 'Kenya');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KI', 'Kiribati');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('XK', 'Kosovo');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KW', 'Kuwait');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KG', 'Kyrgyzstan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LA', 'Laos');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LV', 'Latvia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LB', 'Lebanon');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LS', 'Lesotho');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LR', 'Liberia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LY', 'Libya');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LT', 'Lithuania');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LU', 'Luxembourg');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MO', 'Macao SAR China');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MG', 'Madagascar');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MW', 'Malawi');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MY', 'Malaysia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MV', 'Maldives');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ML', 'Mali');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MT', 'Malta');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MH', 'Marshall Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MQ', 'Martinique');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MR', 'Mauritania');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MU', 'Mauritius');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('YT', 'Mayotte');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MX', 'Mexico');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('FM', 'Micronesia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MD', 'Moldova');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MC', 'Monaco');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MN', 'Mongolia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ME', 'Montenegro');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MS', 'Montserrat');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MA', 'Morocco');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MZ', 'Mozambique');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MM', 'Myanmar (Burma)');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NA', 'Namibia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NR', 'Nauru');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NP', 'Nepal');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NL', 'Netherlands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NC', 'New Caledonia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NZ', 'New Zealand');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NI', 'Nicaragua');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NE', 'Niger');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NG', 'Nigeria');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NU', 'Niue');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NF', 'Norfolk Island');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KP', 'North Korea');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MK', 'North Macedonia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('NO', 'Norway');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('OM', 'Oman');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PK', 'Pakistan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PW', 'Palau');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PS', 'Palestinian Territories');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PA', 'Panama');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PG', 'Papua New Guinea');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PY', 'Paraguay');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PE', 'Peru');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PH', 'Philippines');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PN', 'Pitcairn Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PL', 'Poland');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PT', 'Portugal');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('XA', 'Pseudo-Accents');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('XB', 'Pseudo-Bidi');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PR', 'Puerto Rico');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('QA', 'Qatar');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('RE', 'Réunion');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('RO', 'Romania');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('RU', 'Russia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('RW', 'Rwanda');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('WS', 'Samoa');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SM', 'San Marino');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ST', 'São Tomé & Príncipe');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SA', 'Saudi Arabia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SN', 'Senegal');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('RS', 'Serbia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SC', 'Seychelles');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SG', 'Singapore');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SX', 'Sint Maarten');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SK', 'Slovakia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SI', 'Slovenia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SB', 'Solomon Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SO', 'Somalia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ZA', 'South Africa');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GS', 'South Georgia & South Sandwich Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KR', 'South Korea');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SS', 'South Sudan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ES', 'Spain');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('BL', 'St. Barthélemy');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SH', 'St. Helena');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('KN', 'St. Kitts & Nevis');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('LC', 'St. Lucia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('MF', 'St. Martin');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('PM', 'St. Pierre & Miquelon');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('VC', 'St. Vincent & Grenadines');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SD', 'Sudan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SR', 'Suriname');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SJ', 'Svalbard & Jan Mayen');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SE', 'Sweden');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('CH', 'Switzerland');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('SY', 'Syria');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TW', 'Taiwan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TJ', 'Tajikistan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TZ', 'Tanzania');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TH', 'Thailand');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TL', 'Timor-Leste');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TG', 'Togo');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TK', 'Tokelau');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TO', 'Tonga');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TT', 'Trinidad & Tobago');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TN', 'Tunisia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TR', 'Turkey');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TM', 'Turkmenistan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TC', 'Turks & Caicos Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('TV', 'Tuvalu');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('UM', 'U.S. Outlying Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('VI', 'U.S. Virgin Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('UG', 'Uganda');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('UA', 'Ukraine');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AE', 'United Arab Emirates');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('GB', 'United Kingdom');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('US', 'United States');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('UY', 'Uruguay');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('UZ', 'Uzbekistan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('VU', 'Vanuatu');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('VA', 'Vatican City');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('VE', 'Venezuela');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('VN', 'Vietnam');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('WF', 'Wallis & Futuna');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('EH', 'Western Sahara');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('YE', 'Yemen');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ZM', 'Zambia');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('ZW', 'Zimbabwe');