INSERT INTO "countries" ("country_code", "full_name") VALUES ('AF', 'Afghanistan');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AX', 'Åland Islands');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('AL', 'Albania');
INSERT INTO "countries" ("country_code", "full_name") VALUES ('DZ', 'Algeria');

insert into tour_countries (id, tour_id, country_id) values (1, 1, 1);
insert into tour_countries (id, tour_id, country_id) values (2, 1, 2);
insert into tour_countries (id, tour_id, country_id) values (3, 2, 3);
insert into tour_countries (id, tour_id, country_id) values (8, 2, 4);

insert into tours (id, name, starting_loc, ending_loc, duration, travel_style, listed_price, tagline, description, video, hashtag, accommodation_summary, accommodation_detail, breakfast_included, lunch_included, dinner_included, meals_detail, team_summary, team_detail, transport_summary, transport_detail, experiences_included, experiences_optional, experiences_detail) values (1, 'augue vel', 'Tupesy', 'Lajeosa', 7, 4, 4267, 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'sapien', 'at', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', 3, 4, 3, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 'quis lectus suspendisse potenti in eleifend quam a odio in', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'congue eget semper rutrum nulla nunc purus', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 8, 5, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into tours (id, name, starting_loc, ending_loc, duration, travel_style, listed_price, tagline, description, video, hashtag, accommodation_summary, accommodation_detail, breakfast_included, lunch_included, dinner_included, meals_detail, team_summary, team_detail, transport_summary, transport_detail, experiences_included, experiences_optional, experiences_detail) values (2, 'ut volutpat sapien', 'Libertad', 'Sävedalen', 14, 4, 4604, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'curabitur', 'cras', 'non quam nec dui luctus rutrum nulla tellus in sagittis', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 3, 4, 5, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 'nec dui luctus rutrum nulla tellus in sagittis', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 5, 6, 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');

insert into travel_styles (id, name, description, logo, video) values (1, 'dui maecenas tristique est', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'http://dummyimage.com/400x300.png/dddddd/000000');
insert into travel_styles (id, name, description, logo, video) values (2, 'duis aliquam convallis nunc proin', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'http://dummyimage.com/100x100.png/dddddd/000000', 'http://dummyimage.com/400x300.png/cc0000/ffffff');
insert into travel_styles (id, name, description, logo, video) values (3, 'viverra eget congue eget semper', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://dummyimage.com/100x100.png/dddddd/000000', 'http://dummyimage.com/400x300.png/dddddd/000000');
insert into travel_styles (id, name, description, logo, video) values (4, 'luctus et ultrices posuere cubilia', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'http://dummyimage.com/400x300.png/5fa2dd/ffffff');
insert into travel_styles (id, name, description, logo, video) values (5, 'id nulla ultrices aliquet maecenas', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'http://dummyimage.com/400x300.png/cc0000/ffffff');
insert into travel_styles (id, name, description, logo, video) values (6, 'commodo vulputate justo in blandit', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'http://dummyimage.com/400x300.png/5fa2dd/ffffff');

insert into trips (id, tour_id, start_date, end_date, start_time, end_time, capacity, booked) values (1, 1, '2018-07-12', '2018-07-26', '3:55 PM', '8:46 PM', 16, 2);
insert into trips (id, tour_id, start_date, end_date, start_time, end_time, capacity, booked) values (2, 2, '2018-10-25', '2018-11-08', '1:34 AM', '5:10 PM', 16, 14);
insert into trips (id, tour_id, start_date, end_date, start_time, end_time, capacity, booked) values (3, 1, '2018-06-08', '2018-06-22', '2:27 AM', '9:30 PM', 28, 24);
insert into trips (id, tour_id, start_date, end_date, start_time, end_time, capacity, booked) values (4, 2, '2019-02-14', '2019-02-28', '6:09 AM', '3:10 AM', 29, 11);
insert into trips (id, tour_id, start_date, end_date, start_time, end_time, capacity, booked) values (5, 1, '2019-04-11', '2019-04-25', '12:13 AM', '11:54 PM', 22, 1);